// build.mjs — inline the modular gallery source into the single-page document so
// it runs by double-click (file://), where browsers block ES-module imports
// between local files. Three.js still loads from its https CDN via the importmap.
//
//   run:  node gallery/build.mjs      (from repo root)
//    or:  cd gallery && node build.mjs
//
// Source of truth: gallery/page.htm (document + gallery shell) + gallery/{nd,exhibits,main}.js.
// Output (generated, do not hand-edit): index.htm.

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const read = f => readFileSync(join(here, f), 'utf8');

// 1. nd.js — drop `export` so its names become bundle-scope locals.
const nd = read('nd.js').replace(/^export\s+/gm, '');

// 2. exhibits.js — drop its import, fold the `ND.` namespace into bare calls,
//    and drop `export`.
const exhibits = read('exhibits.js')
  .replace(/^import\s+\*\s+as\s+ND\s+from\s+['"]\.\/nd\.js['"];?\s*$/m, '')
  .replace(/\bND\./g, '')
  .replace(/^export\s+/gm, '');

// 3. main.js — keep the Three.js imports (hoisted to the top of the bundle),
//    drop the local ./nd.js and ./exhibits.js imports (now in scope).
const mainRaw = read('main.js');
const threeImports = [];
const mainBody = [];
for (const line of mainRaw.split('\n')) {
  if (/^import\s.*from\s+['"]three/.test(line)) { threeImports.push(line); continue; }
  if (/^import\s.*from\s+['"]\.\/(nd|exhibits)\.js['"];?\s*$/.test(line)) continue;
  mainBody.push(line);
}

const bundle = [
  '/* GENERATED by gallery/build.mjs — edit gallery/*.js, not this block. */',
  ...threeImports,
  '',
  '/* ===== nd.js ===== */',
  nd,
  '/* ===== exhibits.js ===== */',
  exhibits,
  '/* ===== main.js ===== */',
  mainBody.join('\n'),
].join('\n');

const shell = read('page.htm');
if (!shell.includes('<!--GALLERY_BUNDLE-->'))
  throw new Error('page.htm is missing the <!--GALLERY_BUNDLE--> marker');

const out = shell.replace('<!--GALLERY_BUNDLE-->',
  `<script type="module">\n${bundle}\n</script>`);

const outPath = join(here, '..', 'index.htm');
writeFileSync(outPath, out);
console.log(`Built ${outPath}`);
console.log(`  nd.js       ${nd.length} chars`);
console.log(`  exhibits.js ${exhibits.length} chars`);
console.log(`  main.js     ${mainBody.join('\n').length} chars`);
console.log(`  three imports: ${threeImports.length}`);
