<#
.SYNOPSIS
    Regenerates assets-manifest.json: every runtime asset this repo serves over jsDelivr.
.DESCRIPTION
    Walks the asset folders (one per domain, plus the top-level fonts/ and the component-owned asset dirs),
    and records for each file: its path (the same path appears after @<tag>/ in a jsDelivr URL),
    byte size, SHA-256, and, for raster images, pixel dimensions. Use it to verify that what the
    CDN serves is byte-identical to what is committed (see docs/ASSETS.md).

    The manifest is data, not canon: re-run this script whenever an asset is added, replaced or
    removed, then commit the result with the assets.
.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\build-asset-manifest.ps1
.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\build-asset-manifest.ps1 -Verify
    Exits non-zero if assets-manifest.json is out of date with the files on disk.
#>
[CmdletBinding()]
param(
    [switch]$Verify
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

# Asset roots. A domain folder holds that site's own assets; the top-level fonts/ holds web fonts used by more
# than one site; Components/*/ keeps the runtime files a component owns (textures, fonts bundled with it).
$roots = @(
    'mindattic.com',
    'mindatticcares.com',
    'ryandebraal.com',
    'fonts',
    'Components/Cyberspace/assets'
)
$assetExt = '.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.ico', '.svg', '.woff2', '.woff', '.ttf', '.otf', '.mp3', '.ogg', '.mp4', '.webm', '.json'

Add-Type -AssemblyName System.Drawing

$entries = New-Object System.Collections.ArrayList
foreach ($root in $roots) {
    $abs = Join-Path $repoRoot $root
    if (-not (Test-Path $abs)) { continue }
    Get-ChildItem -Path $abs -Recurse -File |
        Where-Object { $assetExt -contains $_.Extension.ToLowerInvariant() } |
        Sort-Object FullName |
        ForEach-Object {
            $rel = $_.FullName.Substring($repoRoot.Length + 1) -replace '\\', '/'
            $e = [ordered]@{
                path   = $rel
                bytes  = $_.Length
                sha256 = (Get-FileHash -Algorithm SHA256 -Path $_.FullName).Hash.ToLowerInvariant()
            }
            if ('.png', '.jpg', '.jpeg', '.gif' -contains $_.Extension.ToLowerInvariant()) {
                try {
                    $img = [System.Drawing.Image]::FromFile($_.FullName)
                    $e['width'] = $img.Width; $e['height'] = $img.Height
                    $img.Dispose()
                } catch { }
            }
            [void]$entries.Add([pscustomobject]$e)
        }
}

$manifest = [ordered]@{
    '$comment' = 'Generated by tools/build-asset-manifest.ps1. Do not edit by hand. A file is served at https://cdn.jsdelivr.net/gh/mindattic/MindAttic.UiUx@<tag>/<path>.'
    cdnBase    = 'https://cdn.jsdelivr.net/gh/mindattic/MindAttic.UiUx@<tag>/'
    count      = $entries.Count
    totalBytes = ($entries | Measure-Object -Property bytes -Sum).Sum
    files      = $entries
}
$json = ($manifest | ConvertTo-Json -Depth 5) + "`n"
$outPath = Join-Path $repoRoot 'assets-manifest.json'

if ($Verify) {
    $current = if (Test-Path $outPath) { [System.IO.File]::ReadAllText($outPath) } else { '' }
    if (($current -replace "`r`n", "`n") -ne ($json -replace "`r`n", "`n")) {
        Write-Error 'assets-manifest.json is out of date. Run tools\build-asset-manifest.ps1 and commit the result.'
        exit 1
    }
    Write-Host "assets-manifest.json is current ($($entries.Count) files)."
    exit 0
}

[System.IO.File]::WriteAllText($outPath, $json, (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote assets-manifest.json: {0} files, {1:N1} MB" -f $entries.Count, ($manifest.totalBytes / 1MB))
