<#
.SYNOPSIS
  MindAttic Codex CLI for MindAttic.UiUx (code: MAU). Subcommands: doctor, digest.
.DESCRIPTION
  doctor  - validate the Codex docs (front-matter, unique {#ids}, resolvable cross-refs,
            JSON-vs-schema, ✅-story test tokens, cited paths exist, generatedFrom freshness,
            digest up to date). Exits non-zero on any hard error.
  digest  - regenerate docs/BIBLE.digest.md from BIBLE §1, §3, §5, §9 + a status index +
            the latest amendment head.
.NOTES
  Windows PowerShell 5.1 safe. No build step. Run from anywhere:
    powershell -File tools/codex.ps1 doctor
    powershell -File tools/codex.ps1 digest
#>
[CmdletBinding()]
param(
  [Parameter(Position = 0)][ValidateSet('doctor', 'digest')][string]$Command = 'doctor'
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$DocsDir  = Join-Path $RepoRoot 'docs'
$BiblePath   = Join-Path $DocsDir 'BIBLE.md'
$StoriesPath = Join-Path $DocsDir 'USER_STORIES.md'
$AmendPath   = Join-Path $DocsDir 'AMENDMENTS.md'
$DigestPath  = Join-Path $DocsDir 'BIBLE.digest.md'

# ---------- helpers ----------------------------------------------------------
function Read-Text([string]$p) { return [IO.File]::ReadAllText($p) }

function Get-FrontMatter([string]$text) {
  # returns hashtable of the leading --- ... --- YAML block (flat key: value only)
  $h = @{}
  if ($text -notmatch "^(?s)\s*---\r?\n(.*?)\r?\n---") { return $null }
  $block = $Matches[1]
  foreach ($line in ($block -split "\r?\n")) {
    if ($line -match '^\s*([A-Za-z0-9_]+)\s*:\s*(.+?)\s*$') {
      $h[$Matches[1]] = $Matches[2]
    }
  }
  return $h
}

$RequiredFmKeys = @('codex', 'project', 'code', 'layer', 'status', 'updated')

function Test-FrontMatter {
  param([string]$path, [string]$expectLayer, [ref]$errs)
  if (-not (Test-Path $path)) { $errs.Value += "missing file: $path"; return }
  $fm = Get-FrontMatter (Read-Text $path)
  $rel = $path.Substring($RepoRoot.Length + 1)
  if ($null -eq $fm) { $errs.Value += "[$rel] no YAML front-matter block"; return }
  foreach ($k in $RequiredFmKeys) {
    if (-not $fm.ContainsKey($k)) { $errs.Value += "[$rel] front-matter missing key '$k'" }
  }
  if ($fm['codex'] -ne '1') { $errs.Value += "[$rel] front-matter codex must be 1" }
  if ($expectLayer -and $fm['layer'] -ne $expectLayer) {
    $errs.Value += "[$rel] front-matter layer '$($fm['layer'])' != expected '$expectLayer'"
  }
  if ($fm['updated'] -and $fm['updated'] -notmatch '^\d{4}-\d{2}-\d{2}$') {
    $errs.Value += "[$rel] front-matter updated '$($fm['updated'])' is not YYYY-MM-DD"
  }
}

# ---------- DIGEST ------------------------------------------------------------
function Get-Section {
  param([string]$bible, [int]$n)
  # capture "## n. ... {#...}" up to the next "## " (or EOF)
  $pat = "(?ms)^##\s+$n\.\s.*?(?=^##\s+\d+\.|\Z)"
  if ($bible -match $pat) { return $Matches[0].TrimEnd() }
  return $null
}

function Invoke-Digest {
  $bible = Read-Text $BiblePath

  $s1 = Get-Section $bible 1
  $s3 = Get-Section $bible 3
  $s5 = Get-Section $bible 5
  $s9 = Get-Section $bible 9

  # status index: count status glyphs across stories (astral-plane safe)
  $stories = if (Test-Path $StoriesPath) { Read-Text $StoriesPath } else { '' }
  $gDone = [char]::ConvertFromUtf32(0x2705)    # ✅
  $gPart = [char]::ConvertFromUtf32(0x1F7E1)   # 🟡
  $gPlan = [char]::ConvertFromUtf32(0x2B1C)    # ⬜
  $gCut  = [char]::ConvertFromUtf32(0x1F5D1)   # 🗑
  $cDone = ([regex]::Matches($stories, [regex]::Escape($gDone))).Count
  $cPart = ([regex]::Matches($stories, [regex]::Escape($gPart))).Count
  $cPlan = ([regex]::Matches($stories, [regex]::Escape($gPlan))).Count
  $cCut  = ([regex]::Matches($stories, [regex]::Escape($gCut))).Count

  # latest amendment head: first "## CODE-A.. " heading + its first paragraph
  $amendHead = ''
  if (Test-Path $AmendPath) {
    $am = Read-Text $AmendPath
    $ms = [regex]::Matches($am, "(?ms)^##\s+MAU-A\d+\b.*?(?=^##\s+MAU-A\d+\b|\Z)")
    if ($ms.Count -gt 0) { $amendHead = $ms[$ms.Count - 1].Value.TrimEnd() }
  }

  $today = (Get-Date).ToString('yyyy-MM-dd')
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine("AUTHORITATIVE - full detail in docs/BIBLE.md")
  [void]$sb.AppendLine("<!-- GENERATED by tools/codex.ps1 digest. Do not hand-edit. generatedFrom: MAU-§1,§3,§5,§9 -->")
  [void]$sb.AppendLine("<!-- generated: $today -->")
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('# MindAttic.UiUx (MAU) - Bible Digest')
  [void]$sb.AppendLine('> This digest is the session preamble; the full source of truth is docs/BIBLE.md.')
  [void]$sb.AppendLine('> Laws inherit MindAttic.HouseRules.md. Amendments win over the bible.')
  [void]$sb.AppendLine('')
  if ($s1) { [void]$sb.AppendLine($s1); [void]$sb.AppendLine('') }
  if ($s3) { [void]$sb.AppendLine($s3); [void]$sb.AppendLine('') }
  if ($s5) { [void]$sb.AppendLine($s5); [void]$sb.AppendLine('') }
  if ($s9) { [void]$sb.AppendLine($s9); [void]$sb.AppendLine('') }
  [void]$sb.AppendLine('## Status index (from USER_STORIES.md)')
  [void]$sb.AppendLine(("- done: {0} | partial: {1} | planned: {2} | cut: {3}" -f $cDone, $cPart, $cPlan, $cCut))
  [void]$sb.AppendLine('')
  if ($amendHead) {
    [void]$sb.AppendLine('## Latest amendment')
    [void]$sb.AppendLine($amendHead)
    [void]$sb.AppendLine('')
  }

  $out = $sb.ToString()
  [IO.File]::WriteAllText($DigestPath, $out, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host "digest -> docs/BIBLE.digest.md ($([math]::Round($out.Length/1KB,1)) KB)"
}

# ---------- DOCTOR ------------------------------------------------------------
function Invoke-Doctor {
  $errs = @()
  $warns = @()

  # 1. front-matter on every L0/L1/L2/rfc/data file
  Test-FrontMatter $BiblePath   'bible'      ([ref]$errs)
  Test-FrontMatter $StoriesPath 'stories'    ([ref]$errs)
  Test-FrontMatter $AmendPath   'amendments' ([ref]$errs)
  $rfcDir = Join-Path $DocsDir 'rfc'
  if (Test-Path $rfcDir) {
    foreach ($f in Get-ChildItem $rfcDir -Filter '*.md' -File) {
      Test-FrontMatter $f.FullName 'rfc' ([ref]$errs)
    }
  }

  # gather all markdown for id/link analysis
  $mdFiles = @($BiblePath, $StoriesPath, $AmendPath)
  if (Test-Path $rfcDir) { $mdFiles += (Get-ChildItem $rfcDir -Filter '*.md' -File | ForEach-Object FullName) }

  # 2. {#...} anchors unique; cross-ref links resolve
  $anchors = @{}
  foreach ($f in $mdFiles) {
    $t = Read-Text $f
    foreach ($m in [regex]::Matches($t, '\{#([A-Za-z0-9§_.\-]+)\}')) {
      $id = $m.Groups[1].Value
      if ($anchors.ContainsKey($id)) { $errs += "duplicate anchor {#$id} (in $([IO.Path]::GetFileName($f)) and $($anchors[$id]))" }
      else { $anchors[$id] = [IO.Path]::GetFileName($f) }
    }
  }
  # links of the form (...#ID) that target a {#...} anchor (skip MindAttic.HouseRules.md externals & line headings)
  foreach ($f in $mdFiles) {
    $t = Read-Text $f
    foreach ($m in [regex]::Matches($t, '\]\(([^)]*?)#([A-Za-z0-9§_.\-]+)\)')) {
      $target = $m.Groups[1].Value
      $frag   = $m.Groups[2].Value
      if ($target -match 'HouseRules') { continue }   # external, validated separately
      if ($frag -match '^(MAU-§|MAU-LAW-|MAU-US-|MAU-A)') {
        if (-not $anchors.ContainsKey($frag)) { $errs += "[$([IO.Path]::GetFileName($f))] cross-ref #$frag does not resolve to any {#$frag} anchor" }
      }
    }
  }

  # 2b. House-rules references resolve in the shared file
  $housePath = Join-Path (Split-Path -Parent $RepoRoot) 'MindAttic.HouseRules.md'
  if (Test-Path $housePath) {
    $house = Read-Text $housePath
    $houseAnchors = @{}
    foreach ($m in [regex]::Matches($house, '\{#([A-Za-z0-9_\-]+)\}')) { $houseAnchors[$m.Groups[1].Value] = $true }
    foreach ($f in $mdFiles) {
      $t = Read-Text $f
      foreach ($m in [regex]::Matches($t, 'HouseRules\.md#([A-Za-z0-9_\-]+)')) {
        $frag = $m.Groups[1].Value
        if (-not $houseAnchors.ContainsKey($frag)) { $errs += "[$([IO.Path]::GetFileName($f))] HouseRules ref #$frag not found in MindAttic.HouseRules.md" }
      }
    }
  } else {
    $warns += "MindAttic.HouseRules.md not found at $housePath (cannot validate HOUSE-* refs)"
  }

  # 3. data JSON validates against schema (structural: required keys + id pattern + uniqueness)
  $dataDir = Join-Path $DocsDir 'data'
  if (Test-Path $dataDir) {
    $ids = @{}
    foreach ($jf in Get-ChildItem $dataDir -Filter '*.json' -File) {
      try { $json = Get-Content $jf.FullName -Raw | ConvertFrom-Json }
      catch { $errs += "[data/$($jf.Name)] invalid JSON: $($_.Exception.Message)"; continue }
      foreach ($k in @('codex', 'project', 'code', 'layer', 'status', 'updated')) {
        if (-not ($json.PSObject.Properties.Name -contains $k)) { $errs += "[data/$($jf.Name)] missing codex key '$k'" }
      }
      # find an array property and validate entity ids
      foreach ($prop in $json.PSObject.Properties) {
        if ($prop.Value -is [System.Array]) {
          foreach ($e in $prop.Value) {
            if ($e -is [psobject] -and ($e.PSObject.Properties.Name -contains 'id')) {
              $eid = [string]$e.id
              if ($ids.ContainsKey($eid)) { $errs += "[data] duplicate entity id '$eid'" } else { $ids[$eid] = $jf.Name }
            }
          }
        }
      }
    }
    # schema files present for referenced types
    $schemaDir = Join-Path $dataDir '_schema'
    if (-not (Test-Path $schemaDir)) { $warns += "docs/data exists but no _schema/ dir" }
  }

  # 4. every ✅ story names a test token, and that test best-effort exists
  if (Test-Path $StoriesPath) {
    $lines = (Read-Text $StoriesPath) -split "\r?\n"
    $done = [char]::ConvertFromUtf32(0x2705)
    foreach ($ln in $lines) {
      # only inspect actual story bullets: "- **MAU-US-..  ✅** ..."
      if ($ln -match '^\s*-\s+\*\*MAU-US-' -and $ln -match [regex]::Escape($done)) {
        if ($ln -notmatch 'verified by `([^`]+)`') {
          $errs += "[USER_STORIES] a done story names no test: $($ln.Trim().Substring(0,[Math]::Min(80,$ln.Trim().Length)))"
        } else {
          $token = $Matches[1]
          $hit = $false
          foreach ($src in Get-ChildItem $RepoRoot -Recurse -File -Include '*.cs', '*.razor', '*.mjs', '*.js' -ErrorAction SilentlyContinue |
                  Where-Object { $_.FullName -notmatch '\\node_modules\\|\\bin\\|\\obj\\' }) {
            if ((Read-Text $src.FullName) -match [regex]::Escape($token)) { $hit = $true; break }
          }
          if (-not $hit) { $warns += "[USER_STORIES] test token '$token' not found in source tree" }
        }
      }
    }
  }

  # 5. every code path/file cited in the bible exists on disk
  $bible = Read-Text $BiblePath
  $cited = New-Object System.Collections.Generic.HashSet[string]
  foreach ($m in [regex]::Matches($bible, '`([A-Za-z0-9_./\-]+\.(?:ps1|json|cs|razor|js|mjs|css|html|htm|yml|md))`')) {
    [void]$cited.Add($m.Groups[1].Value)
  }
  # sibling repos / out-of-tree prefixes a UiUx-rooted Test-Path can't resolve
  $siblingPrefixes = @('MindAttic.Deploy/', 'MindAttic.Ideas/', 'StreetSamurai/', 'Tutor/', 'MindAttic.Psst/', 'mindattic.com/')
  foreach ($rel in $cited) {
    if ($rel -match '^\.\./') { continue }            # explicit sibling-repo path
    if ($rel -match '[<>*|]') { continue }             # placeholder or glob
    if ($rel -notmatch '/') { continue }               # bare basename cited in prose (e.g. app.css)
    $isSibling = $false
    foreach ($pfx in $siblingPrefixes) { if ($rel.StartsWith($pfx)) { $isSibling = $true; break } }
    if ($isSibling) { continue }
    $full = Join-Path $RepoRoot ($rel -replace '/', '\')
    if (-not (Test-Path $full)) { $errs += "[BIBLE] cited repo path not found on disk: $rel" }
  }

  # 6. generatedFrom / digest freshness
  if (Test-Path $DigestPath) {
    $bibleMt  = (Get-Item $BiblePath).LastWriteTimeUtc
    $digestMt = (Get-Item $DigestPath).LastWriteTimeUtc
    if ($bibleMt -gt $digestMt) { $warns += "BIBLE.digest.md is older than BIBLE.md - run: codex.ps1 digest" }
    # regenerate to a temp and compare content (warn if drifted)
    $cur = Read-Text $DigestPath
    Invoke-Digest | Out-Null
    $new = Read-Text $DigestPath
    $stripCur = ($cur -replace '<!-- generated:.*?-->', '')
    $stripNew = ($new -replace '<!-- generated:.*?-->', '')
    if ($stripCur.Trim() -ne $stripNew.Trim()) { $warns += "BIBLE.digest.md content was out of date (regenerated)" }
  } else {
    $warns += "docs/BIBLE.digest.md missing - run: codex.ps1 digest"
  }

  # ---------- report ----------
  Write-Host ''
  Write-Host '=== Codex doctor: MindAttic.UiUx (MAU) ==='
  Write-Host ("  anchors:        {0}" -f $anchors.Count)
  Write-Host ("  rfc docs:       {0}" -f (@(if (Test-Path $rfcDir) { Get-ChildItem $rfcDir -Filter '*.md' -File }).Count))
  Write-Host ("  data files:     {0}" -f (@(if (Test-Path $dataDir) { Get-ChildItem $dataDir -Filter '*.json' -File }).Count))
  Write-Host ''
  if ($warns.Count) {
    Write-Host ("WARN ({0}):" -f $warns.Count) -ForegroundColor Yellow
    $warns | ForEach-Object { Write-Host "  ! $_" -ForegroundColor Yellow }
    Write-Host ''
  }
  if ($errs.Count) {
    Write-Host ("FAIL ({0} hard error(s)):" -f $errs.Count) -ForegroundColor Red
    $errs | ForEach-Object { Write-Host "  X $_" -ForegroundColor Red }
    exit 1
  }
  Write-Host 'OK - all hard checks passed.' -ForegroundColor Green
  exit 0
}

switch ($Command) {
  'digest' { Invoke-Digest }
  'doctor' { Invoke-Doctor }
}
