# ====================================================================
# MindAttic.Shared -> StreetSamurai
# 1. Overwrites wwwroot/js/{loader,tv-static,home-bg,pin-footer,console-bg}.js
# 2. Rewrites the marker block in wwwroot/app.css with cbg/frontpage.css contents
#
# StreetSamurai's App.razor already <script>-loads the JS files. The first run
# of this script also splices a marker block into app.css; subsequent runs
# replace the marker contents in-place.
#
# Usage:
#   powershell -File sync-streetsamurai.ps1
#   powershell -File sync-streetsamurai.ps1 -BlazorRoot 'D:/path/StreetSamurai.Blazor'
# ====================================================================
[CmdletBinding()]
param(
    [string]$SharedRoot,
    [string]$BlazorRoot = 'D:/Projects/MindAttic/StreetSamurai/v3/StreetSamurai.Blazor'
)

$ErrorActionPreference = 'Stop'

if (-not $SharedRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $SharedRoot = Split-Path -Parent $here
}

$utf8 = [System.Text.UTF8Encoding]::new($false)

$cbg    = Join-Path $SharedRoot 'cbg'
$wwwJs  = Join-Path $BlazorRoot 'wwwroot/js'
$appCss = Join-Path $BlazorRoot 'wwwroot/app.css'

foreach ($p in @($cbg, $wwwJs, $appCss)) {
    if (-not (Test-Path $p)) { throw "Path not found: $p" }
}

# JS files: straight byte-level overwrite (Copy-Item preserves bytes)
$jsFiles = @('loader.js', 'tv-static.js', 'home-bg.js', 'pin-footer.js', 'console-bg.js')
foreach ($f in $jsFiles) {
    Copy-Item -Path (Join-Path $cbg $f) -Destination (Join-Path $wwwJs $f) -Force
    $kb = [math]::Round(((Get-Item (Join-Path $wwwJs $f)).Length / 1024), 1)
    Write-Output "  [JS]  $f  ($kb KB)"
}

# CSS: rewrite marker block in app.css. Use UTF-8 reads to preserve non-ASCII.
$css     = [System.IO.File]::ReadAllText((Join-Path $cbg 'frontpage.css'), $utf8)
$cssText = [System.IO.File]::ReadAllText($appCss, $utf8)

$begin = '/* == BEGIN MINDATTIC.SHARED:CBG.CSS == */'
$end   = '/* == END MINDATTIC.SHARED:CBG.CSS == */'

if (-not $cssText.Contains($begin)) {
    throw "Marker '$begin' not found in $appCss. Insert the marker pair manually first (delete the CBG section it replaces), then re-run sync."
}

$block = $begin + "`r`n" +
         "/* Generated by MindAttic.Shared/sync/sync-streetsamurai.ps1. Do not edit by hand." + "`r`n" +
         "   Edit MindAttic.Shared/cbg/frontpage.css and re-run the sync. */" + "`r`n" +
         $css + "`r`n" +
         $end

$startIdx = $cssText.IndexOf($begin)
$endIdx   = $cssText.IndexOf($end, $startIdx)
if ($endIdx -lt 0) { throw "End marker '$end' not found after begin marker in $appCss." }
$endIdx  += $end.Length

$updated = $cssText.Substring(0, $startIdx) + $block + $cssText.Substring($endIdx)
[System.IO.File]::WriteAllText($appCss, $updated, $utf8)

$kb = [math]::Round(((Get-Item $appCss).Length / 1024), 1)
Write-Output "  [CSS] app.css marker block updated ($kb KB)"
Write-Output "Synced MindAttic.Shared -> $BlazorRoot"
