# ====================================================================
# MindAttic.UiUx -> landing-page subscribers
# --------------------------------------------------------------------
# Generic splicer for project landing pages at mindattic.com/<lowercase>/.
# Each landing-page subscriber in subscribers.json names the target
# index.htm and which components flow into it (typically OutfitFont,
# AtticFont, Cyberspace, BackHomeM).
#
# Usage:
#   powershell -File sync-landing-page.ps1                       # syncs every landing-page subscriber
#   powershell -File sync-landing-page.ps1 -Subscriber IdiotProof
#   powershell -File sync-landing-page.ps1 -Subscriber IdiotProof `
#              -TargetIndex 'D:/Projects/MindAttic/IdiotProof/index.htm'
#
# Add a new landing page by adding a "kind": "landing-page" entry under
# subscribers in subscribers.json -- no script changes required. The
# bare invocation (no -Subscriber) makes this script callable by
# sync-all.ps1 like every other sync-*.ps1, even though it services
# many subscribers rather than one.
# ====================================================================
[CmdletBinding()]
param(
    [string]$Subscriber,
    [string]$ContentRoot,
    [string]$TargetIndex
)

$ErrorActionPreference = 'Stop'

if (-not $ContentRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ContentRoot = Split-Path -Parent $here
}

. (Join-Path $PSScriptRoot '_subscribers.ps1')

$utf8 = [System.Text.UTF8Encoding]::new($false)

# Resolve the set of subscribers we're driving. With -Subscriber we sync
# exactly one (legacy single-target shape). Without it we discover every
# landing-page subscriber in subscribers.json and recurse into a fresh
# invocation per subscriber -- so the per-subscriber output stays grouped
# and a single bad target doesn't take down the rest.
if (-not $Subscriber) {
    if ($TargetIndex) { throw "-TargetIndex requires -Subscriber (target only makes sense for a specific subscriber)." }
    $cfg = Get-SubscribersConfig -ContentRoot $ContentRoot
    $landingNames = @(
        $cfg.subscribers.PSObject.Properties |
            Where-Object { $_.Value.kind -eq 'landing-page' } |
            ForEach-Object { $_.Name }
    )
    if (-not $landingNames -or $landingNames.Count -eq 0) {
        Write-Output "No landing-page subscribers registered. Nothing to do."
        return
    }
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $self = Join-Path $here 'sync-landing-page.ps1'
    $failed = @()
    foreach ($name in $landingNames) {
        Write-Output ""
        Write-Output "--- $name ---"
        try {
            & $self -Subscriber $name -ContentRoot $ContentRoot
        } catch {
            Write-Output "  FAILED: $($_.Exception.Message)"
            $failed += $name
        }
    }
    if ($failed.Count -gt 0) {
        throw "Landing-page sync failed for: $($failed -join ', ')"
    }
    return
}

$sub = Get-Subscriber -Name $Subscriber -ContentRoot $ContentRoot

if ($sub.kind -ne 'landing-page') {
    throw "Subscriber '$Subscriber' has kind '$($sub.kind)', expected 'landing-page'. Use the matching sync script instead."
}

if (-not $TargetIndex) { $TargetIndex = $sub.target }
if (-not (Test-Path $TargetIndex)) { throw "Target not found: $TargetIndex" }

# --------------------------------------------------------------------
# Per-component builders.
# --------------------------------------------------------------------

function Build-FontBlock {
    param(
        [PSCustomObject]$Component,
        [PSCustomObject]$Subscription,
        [string]$ContentRoot,
        [string]$StyleId
    )
    $html = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.htmlFile), $utf8)

    $args = @{ Component = $Component; ContentRoot = $ContentRoot; Encoding = $utf8 }
    if ($Subscription.PSObject.Properties.Name -contains 'applyToSelector') {
        $args['SelectorOverride'] = $Subscription.applyToSelector
    }
    $cssWithApply = Build-FontCssBody @args

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-landing-page.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/subscribers.json + the matching component folder, then re-run the sync. -->" + "`r`n" +
             $html + "`r`n" +
             '<style id="' + $StyleId + '">' + "`r`n" +
             $cssWithApply + "`r`n" +
             '</style>'

    return [pscustomobject]@{ Block = $block; KbDetail = "html $([math]::Round($html.Length / 1024, 1)) KB, css $([math]::Round($cssWithApply.Length / 1024, 1)) KB" }
}

function Build-CyberspaceBlock {
    param([PSCustomObject]$Component, [string]$ContentRoot)

    $html = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.htmlFile), $utf8)
    $css  = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.cssFile),  $utf8)

    $texOverride = ''
    if ($Component.PSObject.Properties.Name -contains 'assetsDir') {
        $texDir = Join-Path $ContentRoot $Component.assetsDir
        if (Test-Path $texDir) {
            $texSrcs = @('circuitboard.00.png', 'circuitboard.01.png', 'circuitboard.02.png')
            $dataUris = $texSrcs | ForEach-Object {
                $tp = Join-Path $texDir $_
                if (Test-Path $tp) {
                    $bytes = [System.IO.File]::ReadAllBytes($tp)
                    $b64   = [Convert]::ToBase64String($bytes)
                    "'data:image/png;base64,$b64'"
                } else { "null" }
            }
            $texOverride = "/* ---- circuitboard textures (base64 inline) ---- */`r`n" +
                           "window.__cyberspaceCircuitboardSrcs = [`r`n  " + ($dataUris -join ",`r`n  ") + "`r`n];`r`n"
        }
    }

    $jsConcat = $texOverride + "`r`n" + (($Component.jsFiles | ForEach-Object {
        "/* ---- $(Split-Path -Leaf $_) ---- */`r`n" + [System.IO.File]::ReadAllText((Join-Path $ContentRoot $_), $utf8)
    }) -join "`r`n`r`n")

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-landing-page.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/Components/Cyberspace/* and re-run the sync. -->" + "`r`n" +
             $html + "`r`n" +
             '<style id="mindattic-components-cyberspace-css">' + "`r`n" +
             $css + "`r`n" +
             '</style>' + "`r`n" +
             '<script id="mindattic-components-cyberspace-js">' + "`r`n" +
             $jsConcat + "`r`n" +
             '</script>'

    return [pscustomobject]@{ Block = $block; KbDetail = "html $([math]::Round($html.Length / 1024, 1)) KB, css $([math]::Round($css.Length / 1024, 1)) KB, $($Component.jsFiles.Count) JS $([math]::Round($jsConcat.Length / 1024, 1)) KB" }
}

function Build-StaticCssBlock {
    param(
        [PSCustomObject]$Component,
        [string]$ContentRoot,
        [string]$StyleId
    )
    $css = Build-StaticCssBody -Component $Component -ContentRoot $ContentRoot -Encoding $utf8

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-landing-page.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/subscribers.json + the matching component folder, then re-run the sync. -->" + "`r`n" +
             '<style id="' + $StyleId + '">' + "`r`n" +
             $css + "`r`n" +
             '</style>'

    return [pscustomobject]@{ Block = $block; KbDetail = "css $([math]::Round($css.Length / 1024, 1)) KB" }
}

function Splice-MarkerBlock {
    param([string]$IndexText, [string]$BeginMarker, [string]$EndMarker, [string]$Block)
    if (-not $IndexText.Contains($BeginMarker)) {
        throw "Marker '$BeginMarker' not found in target. Insert the marker pair manually first, then re-run sync."
    }
    $startIdx = $IndexText.IndexOf($BeginMarker)
    $endIdx   = $IndexText.IndexOf($EndMarker, $startIdx)
    if ($endIdx -lt 0) { throw "End marker '$EndMarker' not found after begin marker." }
    $endIdx  += $EndMarker.Length

    $combined = $BeginMarker + "`r`n" + $Block + "`r`n" + $EndMarker
    return $IndexText.Substring(0, $startIdx) + $combined + $IndexText.Substring($endIdx)
}

# --------------------------------------------------------------------
# Iterate subscriptions
# --------------------------------------------------------------------
$indexText = [System.IO.File]::ReadAllText($TargetIndex, $utf8)
$summary   = New-Object System.Collections.Generic.List[string]

foreach ($subscription in $sub.subscriptions) {
    $comp = Get-ComponentDescriptor -Name $subscription.component -ContentRoot $ContentRoot

    $info = switch ($comp.name) {
        'OutfitFont' { Build-FontBlock      -Component $comp -Subscription $subscription -ContentRoot $ContentRoot -StyleId 'mindattic-components-outfit-font-css' }
        'AtticFont'  { Build-FontBlock      -Component $comp -Subscription $subscription -ContentRoot $ContentRoot -StyleId 'mindattic-components-attic-font-css'  }
        'Cyberspace' { Build-CyberspaceBlock -Component $comp -ContentRoot $ContentRoot }
        'BackHomeM'  { Build-StaticCssBlock  -Component $comp -ContentRoot $ContentRoot -StyleId 'mindattic-components-back-home-m-css' }
        default      { throw "landing-page sync has no builder for component '$($comp.name)'. Add a dispatch case in sync-landing-page.ps1." }
    }

    $beginMarker = "<!-- BEGIN MINDATTIC.UIUX:$($comp.marker) -->"
    $endMarker   = "<!-- END MINDATTIC.UIUX:$($comp.marker) -->"
    $indexText = Splice-MarkerBlock -IndexText $indexText -BeginMarker $beginMarker -EndMarker $endMarker -Block $info.Block

    $summary.Add(("  {0,-12} {1}" -f "$($comp.name):", $info.KbDetail))
}

[System.IO.File]::WriteAllText($TargetIndex, $indexText, $utf8)

$sizeKb = [math]::Round(((Get-Item $TargetIndex).Length / 1024), 1)
Write-Output "Synced MindAttic.UiUx -> $TargetIndex ($sizeKb KB total)"
$summary | ForEach-Object { Write-Output $_ }
