# ====================================================================
# MindAttic.UiUx -> Tutor
# --------------------------------------------------------------------
# Drives Tutor.Blazor's wwwroot from MindAttic.UiUx/subscribers.json.
# Splice-in-place, identical model to sync-prose.ps1:
#   - OutfitFont / AtticFont -> CSS marker block in wwwroot/app.css
#   - html-bundle components  -> jsFiles copied to wwwroot/js + CSS marker block
#
# The shared auth-visual components (UserLogin / UserCircle / UserTimeout) are
# added to subscribers."Tutor".subscriptions once they are authored under
# Components/, along with a matching dispatch case below and a marker pair in
# wwwroot/app.css. Until then the subscription list is empty and this is a no-op.
#
# NOTE: Tutor.Blazor has no wwwroot yet. The first time a subscription is added,
# create wwwroot/app.css (with the marker pairs) and let this script create
# wwwroot/js.
#
# Usage:
#   powershell -File sync-tutor.ps1
#   powershell -File sync-tutor.ps1 -BlazorRoot 'D:/path/Tutor.Blazor'
# ====================================================================
[CmdletBinding()]
param(
    [string]$ContentRoot,
    [string]$BlazorRoot
)

$ErrorActionPreference = 'Stop'

if (-not $ContentRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ContentRoot = Split-Path -Parent $here
}

. (Join-Path $PSScriptRoot '_subscribers.ps1')

$utf8 = [System.Text.UTF8Encoding]::new($false)
$sub  = Get-Subscriber -Name 'Tutor' -ContentRoot $ContentRoot

# No subscriptions yet -> nothing to splice. Keeps sync-all.ps1 green before the
# shared auth components are authored and wired into subscribers.json.
if (-not $sub.subscriptions -or @($sub.subscriptions).Count -eq 0) {
    Write-Output "  Tutor: no subscriptions yet -- nothing to sync."
    return
}

if (-not $BlazorRoot) { $BlazorRoot = $sub.target }

$wwwJs  = Join-Path $BlazorRoot 'wwwroot/js'
$appCss = Join-Path $BlazorRoot 'wwwroot/app.css'
if (-not (Test-Path $BlazorRoot)) { throw "Path not found: $BlazorRoot" }
if (-not (Test-Path $wwwJs)) { New-Item -ItemType Directory -Force -Path $wwwJs | Out-Null }
if (-not (Test-Path $appCss)) { throw "Path not found: $appCss (create wwwroot/app.css with the marker blocks first)" }

function Splice-CssMarkerBlock {
    param([string]$CssText, [string]$Begin, [string]$End, [string]$Body, [string]$SourcePath)
    $ordinal = [System.StringComparison]::Ordinal
    if (-not $CssText.Contains($Begin)) {
        throw "Marker '$Begin' not found in $SourcePath. Insert the marker pair manually first, then re-run sync."
    }
    $block = $Begin + "`r`n" +
             "/* Generated by MindAttic.UiUx/sync/sync-tutor.ps1. Do not edit by hand." + "`r`n" +
             "   Edit MindAttic.UiUx/subscribers.json + the matching component folder, then re-run the sync. */" + "`r`n" +
             $Body + "`r`n" +
             $End

    $startIdx = $CssText.IndexOf($Begin, $ordinal)
    $endIdx   = $CssText.IndexOf($End, $startIdx, $ordinal)
    if ($endIdx -lt 0) { throw "End marker '$End' not found after begin marker in $SourcePath." }
    $endIdx  += $End.Length
    return $CssText.Substring(0, $startIdx) + $block + $CssText.Substring($endIdx)
}

function Copy-ComponentJsFiles {
    param([PSCustomObject]$Component, [string]$ContentRoot, [string]$DestDir)
    if (-not ($Component.PSObject.Properties.Name -contains 'jsFiles')) { return 0 }
    $count = 0
    foreach ($rel in $Component.jsFiles) {
        $src  = Join-Path $ContentRoot $rel
        $name = Split-Path -Leaf $rel
        $dest = Join-Path $DestDir $name
        Copy-Item -Path $src -Destination $dest -Force
        $kb = [math]::Round(((Get-Item $dest).Length / 1024), 1)
        Write-Host "  [JS]  $name  ($kb KB)"
        $count++
    }
    return $count
}

$cssText = [System.IO.File]::ReadAllText($appCss, $utf8)
$cssEol  = Get-DominantEol -Text $cssText
$summary = New-Object System.Collections.Generic.List[string]

foreach ($subscription in $sub.subscriptions) {
    $comp = Get-ComponentDescriptor -Name $subscription.component -ContentRoot $ContentRoot

    switch ($comp.name) {
        { $_ -in 'OutfitFont', 'AtticFont' } {
            $bodyArgs = @{ Component = $comp; ContentRoot = $ContentRoot; Encoding = $utf8 }
            if ($subscription.PSObject.Properties.Name -contains 'applyToSelector') {
                $bodyArgs['SelectorOverride'] = $subscription.applyToSelector
            }
            $body = Build-FontCssBody @bodyArgs
            $cssText = Splice-CssMarkerBlock -CssText $cssText `
                -Begin "/* == BEGIN MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                -End   "/* == END MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                -Body  $body -SourcePath $appCss
            $summary.Add(("  {0,-12} css {1} KB" -f "$($comp.name):", [math]::Round($body.Length / 1024, 1)))
        }

        { $_ -in 'Cyberspace', 'PinFooter', 'WebSnapshot', 'UserLogin', 'UserCircle', 'UserTimeout' } {
            $count = Copy-ComponentJsFiles -Component $comp -ContentRoot $ContentRoot -DestDir $wwwJs
            if ($comp.PSObject.Properties.Name -contains 'cssFile' -and $comp.cssFile) {
                $css = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $comp.cssFile), $utf8)
                $cssText = Splice-CssMarkerBlock -CssText $cssText `
                    -Begin "/* == BEGIN MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -End   "/* == END MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -Body  $css -SourcePath $appCss
            }
            $summary.Add(("  {0,-12} {1} JS files" -f "$($comp.name):", $count))
        }

        default {
            throw "Tutor has no dispatch for component '$($comp.name)'. Add a case in sync-tutor.ps1."
        }
    }
}

[System.IO.File]::WriteAllText($appCss, (ConvertTo-Eol -Text $cssText -Eol $cssEol), $utf8)

$kb = [math]::Round(((Get-Item $appCss).Length / 1024), 1)
Write-Output "  [CSS] app.css marker blocks updated ($kb KB)"
Write-Output ""
Write-Output "Synced MindAttic.UiUx -> $BlazorRoot"
$summary | ForEach-Object { Write-Output $_ }
