# ====================================================================
# MindAttic.UiUx -> StreetSamurai.Writer + StreetSamurai.Codex
# --------------------------------------------------------------------
# Drives both apps' wwwroot from MindAttic.UiUx/subscribers.json.
# Runs the same component dispatch against each subscriber in turn so
# the two apps are always in sync after every UiUx update.
#
# Usage:
#   powershell -File sync-streetsamurai.ps1
# ====================================================================
[CmdletBinding()]
param(
    [string]$ContentRoot
)

$ErrorActionPreference = 'Stop'

if (-not $ContentRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ContentRoot = Split-Path -Parent $here
}

. (Join-Path $PSScriptRoot '_subscribers.ps1')

$utf8 = [System.Text.UTF8Encoding]::new($false)

function Splice-CssMarkerBlock {
    param([string]$CssText, [string]$Begin, [string]$End, [string]$Body, [string]$SourcePath)
    $ordinal = [System.StringComparison]::Ordinal
    if (-not $CssText.Contains($Begin)) {
        throw "Marker '$Begin' not found in $SourcePath. Insert the marker pair manually first, then re-run sync."
    }
    $block = $Begin + "`r`n" +
             "/* Generated by MindAttic.UiUx/sync/sync-streetsamurai.ps1. Do not edit by hand." + "`r`n" +
             "   Edit MindAttic.UiUx/subscribers.json + the matching component folder, then re-run the sync. */" + "`r`n" +
             $Body + "`r`n" +
             $End

    $startIdx = $CssText.IndexOf($Begin, $ordinal)
    $endIdx   = $CssText.IndexOf($End, $startIdx, $ordinal)
    if ($endIdx -lt 0) { throw "End marker '$End' not found after begin marker in $SourcePath." }
    $endIdx  += $End.Length
    return $CssText.Substring(0, $startIdx) + $block + $CssText.Substring($endIdx)
}

function Copy-ComponentJsFiles {
    param([PSCustomObject]$Component, [string]$ContentRoot, [string]$DestDir)
    if (-not ($Component.PSObject.Properties.Name -contains 'jsFiles')) { return 0 }
    $count = 0
    foreach ($rel in $Component.jsFiles) {
        $src  = Join-Path $ContentRoot $rel
        $name = Split-Path -Leaf $rel
        $dest = Join-Path $DestDir $name
        Copy-Item -Path $src -Destination $dest -Force
        $kb = [math]::Round(((Get-Item $dest).Length / 1024), 1)
        Write-Host "    [JS]  $name  ($kb KB)"
        $count++
    }
    return $count
}

function Sync-Subscriber {
    param([string]$SubscriberName, [string]$ContentRoot)

    $sub       = Get-Subscriber -Name $SubscriberName -ContentRoot $ContentRoot
    $blazorRoot = $sub.target
    $wwwJs     = Join-Path $blazorRoot 'wwwroot/js'
    $appCss    = Join-Path $blazorRoot 'wwwroot/app.css'

    foreach ($p in @($blazorRoot, $wwwJs, $appCss)) {
        if (-not (Test-Path $p)) { throw "[$SubscriberName] Path not found: $p" }
    }

    $cssText = [System.IO.File]::ReadAllText($appCss, $utf8)
    $cssEol  = Get-DominantEol -Text $cssText
    $summary = New-Object System.Collections.Generic.List[string]

    foreach ($subscription in $sub.subscriptions) {
        $comp = Get-ComponentDescriptor -Name $subscription.component -ContentRoot $ContentRoot

        switch ($comp.name) {
            { $_ -in 'OutfitFont', 'AtticFont' } {
                $bodyArgs = @{ Component = $comp; ContentRoot = $ContentRoot; Encoding = $utf8 }
                if ($subscription.PSObject.Properties.Name -contains 'applyToSelector') {
                    $bodyArgs['SelectorOverride'] = $subscription.applyToSelector
                }
                $body = Build-FontCssBody @bodyArgs
                $cssText = Splice-CssMarkerBlock -CssText $cssText `
                    -Begin "/* == BEGIN MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -End   "/* == END MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -Body  $body -SourcePath $appCss
                $summary.Add(("    {0,-12} css {1} KB" -f "$($comp.name):", [math]::Round($body.Length / 1024, 1)))
            }

            'Cyberspace' {
                $count = Copy-ComponentJsFiles -Component $comp -ContentRoot $ContentRoot -DestDir $wwwJs
                $css = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $comp.cssFile), $utf8)
                $cssText = Splice-CssMarkerBlock -CssText $cssText `
                    -Begin "/* == BEGIN MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -End   "/* == END MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -Body  $css -SourcePath $appCss
                $summary.Add(("    {0,-12} {1} JS files, css {2} KB" -f "$($comp.name):", $count, [math]::Round($css.Length / 1024, 1)))
            }

            'PinFooter' {
                $count = Copy-ComponentJsFiles -Component $comp -ContentRoot $ContentRoot -DestDir $wwwJs
                $summary.Add(("    {0,-12} {1} JS files (jsOnly)" -f "$($comp.name):", $count))
            }

            { $_ -in 'UserLogin', 'UserCircle', 'UserTimeout' } {
                $count = Copy-ComponentJsFiles -Component $comp -ContentRoot $ContentRoot -DestDir $wwwJs
                $css = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $comp.cssFile), $utf8)
                $cssText = Splice-CssMarkerBlock -CssText $cssText `
                    -Begin "/* == BEGIN MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -End   "/* == END MINDATTIC.UIUX:$($comp.marker).CSS == */" `
                    -Body  $css -SourcePath $appCss
                $summary.Add(("    {0,-12} {1} JS files, css {2} KB" -f "$($comp.name):", $count, [math]::Round($css.Length / 1024, 1)))
            }

            default {
                throw "StreetSamurai has no dispatch for component '$($comp.name)'. Add a case in sync-streetsamurai.ps1."
            }
        }
    }

    [System.IO.File]::WriteAllText($appCss, (ConvertTo-Eol -Text $cssText -Eol $cssEol), $utf8)
    $kb = [math]::Round(((Get-Item $appCss).Length / 1024), 1)
    Write-Output "  Synced MindAttic.UiUx -> $blazorRoot"
    Write-Output "    [CSS] app.css marker blocks updated ($kb KB)"
    $summary | ForEach-Object { Write-Output $_ }
}

Sync-Subscriber -SubscriberName 'StreetSamurai.Writer' -ContentRoot $ContentRoot
Write-Output ""
Sync-Subscriber -SubscriberName 'StreetSamurai.Codex'  -ContentRoot $ContentRoot
