# ====================================================================
# MindAttic.Components -> StreetSamurai
# --------------------------------------------------------------------
# Drives StreetSamurai's wwwroot from MindAttic.Components/subscribers.json.
# Per-component effect on this subscriber (matched by component name below):
#   - OutfitFont / AtticFont  -> splice CSS marker block in wwwroot/app.css
#                                with applyToSelector taken from subscribers.json
#                                (override) or the font's *.json default.
#   - Cyberspace              -> copy all jsFiles to wwwroot/js, then
#                                splice the CYBERSPACE.CSS marker in app.css
#                                from frontpage.css.
#   - PinFooter               -> copy jsFiles to wwwroot/js only (StreetSamurai
#                                inlines its own equivalent of pin-footer.css
#                                elsewhere; the JSON subscription carries
#                                "jsOnly": true to signal this).
#
# Adding a new component for StreetSamurai requires:
#   1. an entry in subscribers."StreetSamurai".subscriptions (subscribers.json)
#   2. a dispatch case in this script's switch below
#   3. matching marker pair(s) in wwwroot/app.css for any CSS the component
#      contributes (use bootstrap-streetsamurai-appcss.ps1 to insert them
#      the first time).
#
# Usage:
#   powershell -File sync-streetsamurai.ps1
#   powershell -File sync-streetsamurai.ps1 -BlazorRoot 'D:/path/StreetSamurai.Blazor'
# ====================================================================
[CmdletBinding()]
param(
    [string]$ContentRoot,
    [string]$BlazorRoot
)

$ErrorActionPreference = 'Stop'

if (-not $ContentRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ContentRoot = Split-Path -Parent $here
}

. (Join-Path $PSScriptRoot '_subscribers.ps1')

$utf8 = [System.Text.UTF8Encoding]::new($false)
$sub  = Get-Subscriber -Name 'StreetSamurai' -ContentRoot $ContentRoot

if (-not $BlazorRoot) { $BlazorRoot = $sub.target }

$wwwJs  = Join-Path $BlazorRoot 'wwwroot/js'
$appCss = Join-Path $BlazorRoot 'wwwroot/app.css'
foreach ($p in @($BlazorRoot, $wwwJs, $appCss)) {
    if (-not (Test-Path $p)) { throw "Path not found: $p" }
}

function Splice-CssMarkerBlock {
    param([string]$CssText, [string]$Begin, [string]$End, [string]$Body, [string]$SourcePath)
    if (-not $CssText.Contains($Begin)) {
        throw "Marker '$Begin' not found in $SourcePath. Insert the marker pair manually first, then re-run sync."
    }
    $block = $Begin + "`r`n" +
             "/* Generated by MindAttic.Components/sync/sync-streetsamurai.ps1. Do not edit by hand." + "`r`n" +
             "   Edit MindAttic.Components/subscribers.json + the matching component folder, then re-run the sync. */" + "`r`n" +
             $Body + "`r`n" +
             $End

    $startIdx = $CssText.IndexOf($Begin)
    $endIdx   = $CssText.IndexOf($End, $startIdx)
    if ($endIdx -lt 0) { throw "End marker '$End' not found after begin marker in $SourcePath." }
    $endIdx  += $End.Length
    return $CssText.Substring(0, $startIdx) + $block + $CssText.Substring($endIdx)
}

function Copy-ComponentJsFiles {
    param([PSCustomObject]$Component, [string]$ContentRoot, [string]$DestDir)
    if (-not ($Component.PSObject.Properties.Name -contains 'jsFiles')) { return 0 }
    $count = 0
    foreach ($rel in $Component.jsFiles) {
        $src  = Join-Path $ContentRoot $rel
        $name = Split-Path -Leaf $rel
        $dest = Join-Path $DestDir $name
        Copy-Item -Path $src -Destination $dest -Force
        $kb = [math]::Round(((Get-Item $dest).Length / 1024), 1)
        # Write-Host so the status line doesn't pollute the function's return value.
        Write-Host "  [JS]  $name  ($kb KB)"
        $count++
    }
    return $count
}

$cssText = [System.IO.File]::ReadAllText($appCss, $utf8)
$summary = New-Object System.Collections.Generic.List[string]

foreach ($subscription in $sub.subscriptions) {
    $comp = Get-ComponentDescriptor -Name $subscription.component -ContentRoot $ContentRoot

    switch ($comp.name) {
        # Fonts: splice the @font-face CSS (+ optional applyToSelector rule) into app.css.
        { $_ -in 'OutfitFont', 'AtticFont' } {
            $args = @{ Component = $comp; ContentRoot = $ContentRoot; Encoding = $utf8 }
            if ($subscription.PSObject.Properties.Name -contains 'applyToSelector') {
                $args['SelectorOverride'] = $subscription.applyToSelector
            }
            $body = Build-FontCssBody @args
            $cssText = Splice-CssMarkerBlock -CssText $cssText `
                -Begin "/* == BEGIN MINDATTIC.COMPONENTS:$($comp.marker).CSS == */" `
                -End   "/* == END MINDATTIC.COMPONENTS:$($comp.marker).CSS == */" `
                -Body  $body -SourcePath $appCss
            $summary.Add(("  {0,-12} css {1} KB" -f "$($comp.name):", [math]::Round($body.Length / 1024, 1)))
        }

        # Cyberspace: copy the JS files into wwwroot/js, splice its frontpage.css into app.css.
        'Cyberspace' {
            $count = Copy-ComponentJsFiles -Component $comp -ContentRoot $ContentRoot -DestDir $wwwJs
            $css = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $comp.cssFile), $utf8)
            $cssText = Splice-CssMarkerBlock -CssText $cssText `
                -Begin "/* == BEGIN MINDATTIC.COMPONENTS:$($comp.marker).CSS == */" `
                -End   "/* == END MINDATTIC.COMPONENTS:$($comp.marker).CSS == */" `
                -Body  $css -SourcePath $appCss
            $summary.Add(("  {0,-12} {1} JS files, css {2} KB" -f "$($comp.name):", $count, [math]::Round($css.Length / 1024, 1)))
        }

        # PinFooter: JS-only here (StreetSamurai keeps its own pin-footer CSS).
        'PinFooter' {
            $count = Copy-ComponentJsFiles -Component $comp -ContentRoot $ContentRoot -DestDir $wwwJs
            $summary.Add(("  {0,-12} {1} JS files (jsOnly)" -f "$($comp.name):", $count))
        }

        default {
            throw "StreetSamurai has no dispatch for component '$($comp.name)'. Add a case in sync-streetsamurai.ps1."
        }
    }
}

[System.IO.File]::WriteAllText($appCss, $cssText, $utf8)

$kb = [math]::Round(((Get-Item $appCss).Length / 1024), 1)
Write-Output "  [CSS] app.css marker blocks updated ($kb KB)"
Write-Output ""
Write-Output "Synced MindAttic.Components -> $BlazorRoot"
$summary | ForEach-Object { Write-Output $_ }
