# ====================================================================
# MindAttic.UiUx -> mindattic.com
# --------------------------------------------------------------------
# Inlines each MindAttic.UiUx component subscribed to by mindattic.com
# (per subscribers.json) into mindattic.com/index.htm between its own
# marker pair. Each component owns one html + one css + one or more js
# files in its own folder.
#
# Which components flow to mindattic.com -- and per-component config like
# AtticFont's applyToSelector = ".site-name" -- lives in
# MindAttic.UiUx/subscribers.json under subscribers."mindattic.com".
# Edit that file (not this script) to add or remove a subscription.
#
# Component handlers below are matched by component name. Adding support
# for a brand-new component type (e.g. a new effect bundle) requires both
# a registry entry in subscribers.json AND a builder + dispatch case here.
#
# Everything between a group's markers is replaced wholesale every run;
# nothing outside any marker pair is touched. Source of truth is this
# folder tree -- never hand-edit the inlined blocks in index.htm, they
# WILL be overwritten on the next sync (and the next /deploy).
#
# Idempotent: re-running with no source changes produces a byte-stable
# index.htm. Safe to call from deploy pipelines.
#
# Usage:
#   powershell -File sync-mindattic-com.ps1
#   powershell -File sync-mindattic-com.ps1 -TargetIndex 'D:/path/to/index.htm'
#   powershell -File sync-mindattic-com.ps1 -ContentRoot 'D:/path/to/MindAttic.UiUx'
# ====================================================================
[CmdletBinding()]
param(
    [string]$ContentRoot,
    [string]$TargetIndex
)

$ErrorActionPreference = 'Stop'

if (-not $ContentRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ContentRoot = Split-Path -Parent $here
}

. (Join-Path $PSScriptRoot '_subscribers.ps1')

$utf8 = [System.Text.UTF8Encoding]::new($false)
$sub  = Get-Subscriber -Name 'mindattic.com' -ContentRoot $ContentRoot

if (-not $TargetIndex) { $TargetIndex = $sub.target }
if (-not (Test-Path $TargetIndex)) { throw "Target not found: $TargetIndex" }

# --------------------------------------------------------------------
# Per-component builders. Each returns a PSCustomObject with a .Block
# string (what goes between the BEGIN/END markers) plus size fields for
# the status line.
# --------------------------------------------------------------------

function Build-FontBlock {
    param(
        [PSCustomObject]$Component,
        [PSCustomObject]$Subscription,
        [string]$ContentRoot,
        [string]$StyleId
    )
    $folder   = Split-Path -Parent (Join-Path $ContentRoot $Component.cssFile)
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($Component.cssFile)

    $html = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.htmlFile), $utf8)

    $args = @{ Component = $Component; ContentRoot = $ContentRoot; Encoding = $utf8 }
    if ($Subscription.PSObject.Properties.Name -contains 'applyToSelector') {
        $args['SelectorOverride'] = $Subscription.applyToSelector
    }
    $cssWithApply = Build-FontCssBody @args

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-mindattic-com.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/subscribers.json + the matching component folder, then re-run the sync. -->" + "`r`n" +
             $html + "`r`n" +
             '<style id="' + $StyleId + '">' + "`r`n" +
             $cssWithApply + "`r`n" +
             '</style>'

    return [pscustomobject]@{ Block = $block; KbDetail = "html $([math]::Round($html.Length / 1024, 1)) KB, css $([math]::Round($cssWithApply.Length / 1024, 1)) KB" }
}

function Build-CyberspaceBlock {
    param([PSCustomObject]$Component, [string]$ContentRoot)

    $html = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.htmlFile), $utf8)
    $css  = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.cssFile),  $utf8)

    # Inline parallax circuit-board textures as base64 data URIs. console-bg.js
    # reads window.__cyberspaceCircuitboardSrcs if defined; PNG (not JPEG) is
    # required because JPEG block compression breaks the edge-pixel match
    # between adjacent tile copies and produces seams.
    $texOverride = ''
    if ($Component.PSObject.Properties.Name -contains 'assetsDir') {
        $texDir = Join-Path $ContentRoot $Component.assetsDir
        if (Test-Path $texDir) {
            $texSrcs = @('circuitboard.00.png', 'circuitboard.01.png', 'circuitboard.02.png')
            $dataUris = $texSrcs | ForEach-Object {
                $tp = Join-Path $texDir $_
                if (Test-Path $tp) {
                    $bytes = [System.IO.File]::ReadAllBytes($tp)
                    $b64   = [Convert]::ToBase64String($bytes)
                    "'data:image/png;base64,$b64'"
                } else { "null" }
            }
            $texOverride = "/* ---- circuitboard textures (base64 inline) ---- */`r`n" +
                           "window.__cyberspaceCircuitboardSrcs = [`r`n  " + ($dataUris -join ",`r`n  ") + "`r`n];`r`n"
        }
    }

    # JS concat order: loader -> tv-static -> home-bg -> console-bg. Texture
    # override must come BEFORE console-bg.js so its TEX_SRCS picks it up at
    # module-init time.
    $jsConcat = $texOverride + "`r`n" + (($Component.jsFiles | ForEach-Object {
        "/* ---- $(Split-Path -Leaf $_) ---- */`r`n" + [System.IO.File]::ReadAllText((Join-Path $ContentRoot $_), $utf8)
    }) -join "`r`n`r`n")

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-mindattic-com.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/Components/Cyberspace/* and re-run the sync. -->" + "`r`n" +
             $html + "`r`n" +
             '<style id="mindattic-components-cyberspace-css">' + "`r`n" +
             $css + "`r`n" +
             '</style>' + "`r`n" +
             '<script id="mindattic-components-cyberspace-js">' + "`r`n" +
             $jsConcat + "`r`n" +
             '</script>'

    return [pscustomobject]@{ Block = $block; KbDetail = "html $([math]::Round($html.Length / 1024, 1)) KB, css $([math]::Round($css.Length / 1024, 1)) KB, $($Component.jsFiles.Count) JS $([math]::Round($jsConcat.Length / 1024, 1)) KB" }
}

function Build-PinFooterBlock {
    param([PSCustomObject]$Component, [string]$ContentRoot)

    $html = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.htmlFile), $utf8)
    $css  = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.cssFile),  $utf8)
    $js   = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.jsFiles[0]), $utf8)

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-mindattic-com.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/Components/PinFooter/* and re-run the sync. -->" + "`r`n" +
             $html + "`r`n" +
             '<style id="mindattic-components-pin-footer-css">' + "`r`n" +
             $css + "`r`n" +
             '</style>' + "`r`n" +
             '<script id="mindattic-components-pin-footer-js">' + "`r`n" +
             $js + "`r`n" +
             '</script>'

    return [pscustomobject]@{ Block = $block; KbDetail = "html $([math]::Round($html.Length / 1024, 1)) KB, css $([math]::Round($css.Length / 1024, 1)) KB, js $([math]::Round($js.Length / 1024, 1)) KB" }
}

function Build-WebSnapshotBlock {
    param([PSCustomObject]$Component, [string]$ContentRoot)

    $css = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.cssFile), $utf8)
    $js  = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.jsFiles[0]), $utf8)

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-mindattic-com.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/Components/WebSnapshot/* and re-run the sync." + "`r`n" +
             "     Mark any container with class `"web-snapshot`" with either data-src" + "`r`n" +
             "     (fetch a .b64.txt) or an inline <img src=`"data:image/png;base64,...`">. -->" + "`r`n" +
             '<style id="mindattic-components-web-snapshot-css">' + "`r`n" +
             $css + "`r`n" +
             '</style>' + "`r`n" +
             '<script id="mindattic-components-web-snapshot-js">' + "`r`n" +
             $js + "`r`n" +
             '</script>'

    return [pscustomobject]@{ Block = $block; KbDetail = "css $([math]::Round($css.Length / 1024, 1)) KB, js $([math]::Round($js.Length / 1024, 1)) KB" }
}

function Splice-MarkerBlock {
    param([string]$IndexText, [string]$BeginMarker, [string]$EndMarker, [string]$Block)
    if (-not $IndexText.Contains($BeginMarker)) {
        throw "Marker '$BeginMarker' not found in target. Insert the marker pair manually first, then re-run sync."
    }
    $startIdx = $IndexText.IndexOf($BeginMarker)
    $endIdx   = $IndexText.IndexOf($EndMarker, $startIdx)
    if ($endIdx -lt 0) { throw "End marker '$EndMarker' not found after begin marker." }
    $endIdx  += $EndMarker.Length

    $combined = $BeginMarker + "`r`n" + $Block + "`r`n" + $EndMarker
    return $IndexText.Substring(0, $startIdx) + $combined + $IndexText.Substring($endIdx)
}

# --------------------------------------------------------------------
# Iterate subscriptions from subscribers.json
# --------------------------------------------------------------------
$indexText = [System.IO.File]::ReadAllText($TargetIndex, $utf8)
$summary   = New-Object System.Collections.Generic.List[string]

foreach ($subscription in $sub.subscriptions) {
    $comp = Get-ComponentDescriptor -Name $subscription.component -ContentRoot $ContentRoot

    $info = switch ($comp.name) {
        'OutfitFont'  { Build-FontBlock      -Component $comp -Subscription $subscription -ContentRoot $ContentRoot -StyleId 'mindattic-components-outfit-font-css' }
        'AtticFont'   { Build-FontBlock      -Component $comp -Subscription $subscription -ContentRoot $ContentRoot -StyleId 'mindattic-components-attic-font-css'  }
        'Cyberspace'  { Build-CyberspaceBlock  -Component $comp -ContentRoot $ContentRoot }
        'PinFooter'   { Build-PinFooterBlock   -Component $comp -ContentRoot $ContentRoot }
        'WebSnapshot' { Build-WebSnapshotBlock -Component $comp -ContentRoot $ContentRoot }
        default       { throw "mindattic.com has no builder for component '$($comp.name)'. Add a dispatch case in sync-mindattic-com.ps1." }
    }

    $beginMarker = "<!-- BEGIN MINDATTIC.UIUX:$($comp.marker) -->"
    $endMarker   = "<!-- END MINDATTIC.UIUX:$($comp.marker) -->"
    $indexText = Splice-MarkerBlock -IndexText $indexText -BeginMarker $beginMarker -EndMarker $endMarker -Block $info.Block

    $summary.Add(("  {0,-12} {1}" -f "$($comp.name):", $info.KbDetail))
}

[System.IO.File]::WriteAllText($TargetIndex, $indexText, $utf8)

$sizeKb = [math]::Round(((Get-Item $TargetIndex).Length / 1024), 1)
Write-Output "Synced MindAttic.UiUx -> $TargetIndex ($sizeKb KB total)"
$summary | ForEach-Object { Write-Output $_ }
