# ====================================================================
# MindAttic.Shared -> mindattic.com
# Inlines the frontpage/ bundle into mindattic.com/index.htm between
# the BEGIN/END MINDATTIC.SHARED:FRONTPAGE markers.
#
# Idempotent: run as often as you want; result is byte-stable for a
# given MindAttic.Shared revision.
#
# Usage:
#   powershell -File sync-mindattic-com.ps1
#   powershell -File sync-mindattic-com.ps1 -TargetIndex 'D:/path/to/index.htm'
# ====================================================================
[CmdletBinding()]
param(
    [string]$SharedRoot,
    [string]$TargetIndex = 'D:/Projects/MindAttic/mindattic.com/index.htm'
)

$ErrorActionPreference = 'Stop'

if (-not $SharedRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $SharedRoot = Split-Path -Parent $here
}

$utf8 = [System.Text.UTF8Encoding]::new($false)

$fp = Join-Path $SharedRoot 'frontpage'
if (-not (Test-Path $fp))          { throw "frontpage/ not found at $fp" }
if (-not (Test-Path $TargetIndex)) { throw "Target not found: $TargetIndex" }

$html = [System.IO.File]::ReadAllText((Join-Path $fp 'frontpage.html'), $utf8)
$css  = [System.IO.File]::ReadAllText((Join-Path $fp 'frontpage.css'),  $utf8)

# Inline the parallax circuit-board textures as base64 data URIs. console-bg.js
# reads window.__cbgCircuitboardSrcs if defined; StreetSamurai's MediaController
# serves them via /api/media/... instead, so we only emit this override when
# the JPEG assets exist alongside the bundle.
$texSrcs = @('circuitboard.00.jpg', 'circuitboard.01.jpg', 'circuitboard.02.jpg')
$texOverride = ''
$texDir = Join-Path $fp 'assets'
if (Test-Path $texDir) {
    $dataUris = $texSrcs | ForEach-Object {
        $tp = Join-Path $texDir $_
        if (Test-Path $tp) {
            $bytes = [System.IO.File]::ReadAllBytes($tp)
            $b64   = [Convert]::ToBase64String($bytes)
            "'data:image/jpeg;base64,$b64'"
        } else { "null" }
    }
    $texOverride = "/* ---- circuitboard textures (base64 inline) ---- */`r`n" +
                   "window.__cbgCircuitboardSrcs = [`r`n  " + ($dataUris -join ",`r`n  ") + "`r`n];`r`n"
}

# Concatenate JS in the same order StreetSamurai loads them. loader.js + tv-static.js
# expose tiny globals that console-bg.js / page navigation may reach for; home-bg.js
# only exposes window.homeBg (idle unless invoked); scan-glitch.js self-starts on load;
# console-bg.js does the heavy lifting. The texture override (if any) must come
# before console-bg.js so its TEX_SRCS picks it up at module-init time.
$jsParts = @('loader.js', 'tv-static.js', 'home-bg.js', 'scan-glitch.js', 'console-bg.js')
$jsConcat = $texOverride + "`r`n" + (($jsParts | ForEach-Object {
    "/* ---- $_ ---- */`r`n" + [System.IO.File]::ReadAllText((Join-Path $fp $_), $utf8)
}) -join "`r`n`r`n")

$begin = '<!-- BEGIN MINDATTIC.SHARED:FRONTPAGE -->'
$end   = '<!-- END MINDATTIC.SHARED:FRONTPAGE -->'

$block = $begin + "`r`n" +
         "<!-- Generated by MindAttic.Shared/sync/sync-mindattic-com.ps1. Do not edit by hand." + "`r`n" +
         "     Edit MindAttic.Shared/frontpage/* and re-run the sync. -->" + "`r`n" +
         $html + "`r`n" +
         '<style id="mindattic-shared-frontpage-css">' + "`r`n" +
         $css + "`r`n" +
         '</style>' + "`r`n" +
         '<script id="mindattic-shared-frontpage-js">' + "`r`n" +
         $jsConcat + "`r`n" +
         '</script>' + "`r`n" +
         $end

$indexText = [System.IO.File]::ReadAllText($TargetIndex, $utf8)

if (-not $indexText.Contains($begin)) {
    throw "Marker '$begin' not found in $TargetIndex. Insert the marker pair manually first, then re-run sync."
}

$startIdx = $indexText.IndexOf($begin)
$endIdx   = $indexText.IndexOf($end, $startIdx)
if ($endIdx -lt 0) { throw "End marker '$end' not found after begin marker in $TargetIndex." }
$endIdx  += $end.Length

$updated = $indexText.Substring(0, $startIdx) + $block + $indexText.Substring($endIdx)
[System.IO.File]::WriteAllText($TargetIndex, $updated, $utf8)

$sizeKb   = [math]::Round(((Get-Item $TargetIndex).Length / 1024), 1)
$htmlKb   = [math]::Round($html.Length / 1024, 1)
$cssKb    = [math]::Round($css.Length / 1024, 1)
$jsKb     = [math]::Round($jsConcat.Length / 1024, 1)
Write-Output "Synced MindAttic.Shared -> $TargetIndex ($sizeKb KB total)"
Write-Output "Inlined: html ($htmlKb KB), css ($cssKb KB), 5 JS files ($jsKb KB)"
