# ====================================================================
# MindAttic.UiUx -> MindAttic.Psst
# --------------------------------------------------------------------
# Inlines each MindAttic.UiUx component subscribed to by
# MindAttic.Psst (per subscribers.json) into every file listed in the
# subscriber's `targets` array (relative to `target` = project root).
# Currently those targets are privacy.htm and terms.htm; each gets the
# same marker-pair splice so both pages render in Outfit.
#
# Which components flow to MindAttic.Psst -- and per-component config --
# lives in MindAttic.UiUx/subscribers.json under
# subscribers."MindAttic.Psst". Edit that file (not this script) to add
# or remove a subscription.
#
# Subscriber kind: `html-inline-multi`. Same splice rules as
# sync-mindattic-com.ps1's `html-inline`, but the script loops over a
# `targets` array of HTM files within the project root rather than
# touching a single file.
#
# Everything between a group's markers is replaced wholesale every run;
# nothing outside any marker pair is touched. Source of truth is this
# folder tree -- never hand-edit the inlined blocks in privacy.htm /
# terms.htm, they WILL be overwritten on the next sync.
#
# Idempotent: re-running with no source changes produces byte-stable
# output. Safe to call from deploy pipelines.
#
# Usage:
#   powershell -File sync-mindattic-psst.ps1
#   powershell -File sync-mindattic-psst.ps1 -TargetRoot 'D:/path/to/MindAttic.Psst'
#   powershell -File sync-mindattic-psst.ps1 -ContentRoot 'D:/path/to/MindAttic.UiUx'
# ====================================================================
[CmdletBinding()]
param(
    [string]$ContentRoot,
    [string]$TargetRoot
)

$ErrorActionPreference = 'Stop'

if (-not $ContentRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ContentRoot = Split-Path -Parent $here
}

. (Join-Path $PSScriptRoot '_subscribers.ps1')

$utf8 = [System.Text.UTF8Encoding]::new($false)
$sub  = Get-Subscriber -Name 'MindAttic.Psst.Legal' -ContentRoot $ContentRoot

if (-not $TargetRoot) { $TargetRoot = $sub.target }
if (-not (Test-Path $TargetRoot)) { throw "Target root not found: $TargetRoot" }
if (-not $sub.PSObject.Properties.Name -contains 'targets') { throw "MindAttic.Psst subscriber missing 'targets' array in subscribers.json" }

# --------------------------------------------------------------------
# Per-component builders. Mirrors sync-mindattic-com.ps1 but trimmed to
# the components MindAttic.Psst actually subscribes to. Add a builder +
# dispatch case below if a new component type joins the subscription.
# --------------------------------------------------------------------

function Build-FontBlock {
    param(
        [PSCustomObject]$Component,
        [PSCustomObject]$Subscription,
        [string]$ContentRoot,
        [string]$StyleId
    )
    $html = [System.IO.File]::ReadAllText((Join-Path $ContentRoot $Component.htmlFile), $utf8)

    $args = @{ Component = $Component; ContentRoot = $ContentRoot; Encoding = $utf8 }
    if ($Subscription.PSObject.Properties.Name -contains 'applyToSelector') {
        $args['SelectorOverride'] = $Subscription.applyToSelector
    }
    $cssWithApply = Build-FontCssBody @args

    $block = "<!-- Generated by MindAttic.UiUx/sync/sync-mindattic-psst.ps1. Do not edit by hand." + "`r`n" +
             "     Edit MindAttic.UiUx/subscribers.json + the matching component folder, then re-run the sync. -->" + "`r`n" +
             $html + "`r`n" +
             '<style id="' + $StyleId + '">' + "`r`n" +
             $cssWithApply + "`r`n" +
             '</style>'

    return [pscustomobject]@{ Block = $block; KbDetail = "html $([math]::Round($html.Length / 1024, 1)) KB, css $([math]::Round($cssWithApply.Length / 1024, 1)) KB" }
}

function Splice-MarkerBlock {
    param([string]$IndexText, [string]$BeginMarker, [string]$EndMarker, [string]$Block)
    if (-not $IndexText.Contains($BeginMarker)) {
        throw "Marker '$BeginMarker' not found in target. Insert the marker pair manually first, then re-run sync."
    }
    $startIdx = $IndexText.IndexOf($BeginMarker)
    $endIdx   = $IndexText.IndexOf($EndMarker, $startIdx)
    if ($endIdx -lt 0) { throw "End marker '$EndMarker' not found after begin marker." }
    $endIdx  += $EndMarker.Length

    $combined = $BeginMarker + "`r`n" + $Block + "`r`n" + $EndMarker
    return $IndexText.Substring(0, $startIdx) + $combined + $IndexText.Substring($endIdx)
}

# --------------------------------------------------------------------
# For each target file under $TargetRoot, splice every subscription's
# marker block. A missing marker pair in any one file aborts the run --
# fix the file (insert the pair once) and re-run.
# --------------------------------------------------------------------
$summary = New-Object System.Collections.Generic.List[string]

foreach ($relPath in $sub.targets) {
    $targetFile = Join-Path $TargetRoot $relPath
    if (-not (Test-Path $targetFile)) { throw "Target file not found: $targetFile" }

    $indexText = [System.IO.File]::ReadAllText($targetFile, $utf8)

    foreach ($subscription in $sub.subscriptions) {
        $comp = Get-ComponentDescriptor -Name $subscription.component -ContentRoot $ContentRoot

        $info = switch ($comp.name) {
            'OutfitFont' { Build-FontBlock -Component $comp -Subscription $subscription -ContentRoot $ContentRoot -StyleId 'mindattic-components-outfit-font-css' }
            'AtticFont'  { Build-FontBlock -Component $comp -Subscription $subscription -ContentRoot $ContentRoot -StyleId 'mindattic-components-attic-font-css'  }
            default      { throw "MindAttic.Psst has no builder for component '$($comp.name)'. Add a dispatch case in sync-mindattic-psst.ps1." }
        }

        $beginMarker = "<!-- BEGIN MINDATTIC.UIUX:$($comp.marker) -->"
        $endMarker   = "<!-- END MINDATTIC.UIUX:$($comp.marker) -->"
        $indexText   = Splice-MarkerBlock -IndexText $indexText -BeginMarker $beginMarker -EndMarker $endMarker -Block $info.Block
    }

    [System.IO.File]::WriteAllText($targetFile, $indexText, $utf8)
    $sizeKb = [math]::Round(((Get-Item $targetFile).Length / 1024), 1)
    $summary.Add(("  {0,-14} {1} KB" -f "$($relPath):", $sizeKb))
}

Write-Output "Synced MindAttic.UiUx -> MindAttic.Psst ($TargetRoot)"
$summary | ForEach-Object { Write-Output $_ }
