# ====================================================================
# MindAttic.UiUx -> ChiMesh
# --------------------------------------------------------------------
# Splices CSS marker blocks into ChiMesh's scripts/cli/build-html.js
# inside the <style> template literal. The list of marker blocks and
# the per-subscription configuration (e.g. AtticFont's applyToSelector
# = "#chimesh") all live in MindAttic.UiUx/subscribers.json under
# subscribers.ChiMesh.subscriptions. Add or remove entries there; this
# script automatically iterates the list.
#
# Every subsequent `node scripts/cli/build-html.js` run inherits the
# fresh CSS into ChiMesh.htm / index.htm.
#
# The marker pairs must already exist in build-html.js -- they're
# inserted manually once (immediately after the opening `<style>`),
# then this script keeps them current.
#
# Usage:
#   powershell -File sync-chimesh.ps1
#   powershell -File sync-chimesh.ps1 -ChiMeshRoot 'D:/path/ChiMesh'
# ====================================================================
[CmdletBinding()]
param(
    [string]$ContentRoot,
    [string]$ChiMeshRoot
)

$ErrorActionPreference = 'Stop'

if (-not $ContentRoot) {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ContentRoot = Split-Path -Parent $here
}

. (Join-Path $PSScriptRoot '_subscribers.ps1')

$utf8 = [System.Text.UTF8Encoding]::new($false)
$sub  = Get-Subscriber -Name 'ChiMesh' -ContentRoot $ContentRoot

$buildScript = if ($ChiMeshRoot) { Join-Path $ChiMeshRoot 'scripts/cli/build-html.js' } else { $sub.target }
if (-not (Test-Path $buildScript)) { throw "Path not found: $buildScript" }

function Splice-CssMarkerBlock {
    param(
        [string]$Text,
        [string]$Begin,
        [string]$End,
        [string]$Body,
        [string]$SourcePath
    )
    if (-not $Text.Contains($Begin)) {
        throw "Marker '$Begin' not found in $SourcePath. Insert the marker pair manually inside the <style> template literal, then re-run sync."
    }
    $block = $Begin + "`r`n" +
             "/* Generated by MindAttic.UiUx/sync/sync-chimesh.ps1. Do not edit by hand." + "`r`n" +
             "   Edit MindAttic.UiUx/subscribers.json and the matching component folder, then re-run the sync. */" + "`r`n" +
             $Body + "`r`n" +
             $End

    $startIdx = $Text.IndexOf($Begin)
    $endIdx   = $Text.IndexOf($End, $startIdx)
    if ($endIdx -lt 0) { throw "End marker '$End' not found after begin marker in $SourcePath." }
    $endIdx  += $End.Length

    return $Text.Substring(0, $startIdx) + $block + $Text.Substring($endIdx)
}

$text = [System.IO.File]::ReadAllText($buildScript, $utf8)

foreach ($subscription in $sub.subscriptions) {
    $comp = Get-ComponentDescriptor -Name $subscription.component -ContentRoot $ContentRoot

    $body = switch ($comp.type) {
        'font-css' {
            $args = @{ Component = $comp; ContentRoot = $ContentRoot }
            if ($subscription.PSObject.Properties.Name -contains 'applyToSelector') {
                $args['SelectorOverride'] = $subscription.applyToSelector
            }
            Build-FontCssBody @args
        }
        'static-css' { Build-StaticCssBody -Component $comp -ContentRoot $ContentRoot }
        default       { throw "Component '$($comp.name)' has type '$($comp.type)', which is not supported by build-html-js subscribers." }
    }

    $begin = "/* == BEGIN MINDATTIC.UIUX:$($comp.marker).CSS == */"
    $end   = "/* == END MINDATTIC.UIUX:$($comp.marker).CSS == */"
    $safeBody = $body | ConvertTo-JsTemplateLiteralSafe
    $text = Splice-CssMarkerBlock -Text $text -Begin $begin -End $end -Body $safeBody -SourcePath $buildScript
    Write-Output ("  [{0,-10}] spliced ($([math]::Round($body.Length / 1024, 1)) KB)" -f $comp.name)
}

[System.IO.File]::WriteAllText($buildScript, $text, $utf8)
$kb = [math]::Round(((Get-Item $buildScript).Length / 1024), 1)
Write-Output ""
Write-Output "Synced MindAttic.UiUx -> $buildScript ($kb KB total)"
Write-Output "Run 'node scripts/cli/build-html.js' in $(Split-Path -Parent (Split-Path -Parent $buildScript)) to materialize into ChiMesh.htm / index.htm."
